### ISSUE TITLE
7.6 LTS Release

### ISSUE THREAD

**Issue by sneopu** [svewap/ws_less#18]
It would be nice to have a finale release  for TYPO3 7.6 LTS in the TER. As far as I can see the current master branch is fully compatible with 7.6 LTS.

**Comment by svewap** [comment]
Thanks! I will release a new version if I will have a few free minutes!

**Comment by sneopu** [comment]
Hi. Please take some minutes. It would be great. Thanks.

**Comment by sneopu** [comment]
Hey Sven. I know it is open source and work in your spare time. But a final release in the TER for 7.6 LTS would be very nice. Thanks in advance. Cheers Steph
