### ISSUE TITLE
Breaking in TYPO3 8.x

### ISSUE THREAD

**Issue by oliverschloebe** [svewap/ws_less#24]
Hi,

some namespaces such as `\TYPO3\CMS\Core\Core\Environment` and `\TYPO3\CMS\Frontend\Resource\FilePathSanitizer` are not available in TYPO3 < 9 so updating the extension from 1.4.x to 1.5.x will currently break in TYPO3 8 installations.

Just noticed you already upped TYPO3's minimum version in the `composer.json` file (https://github.com/svewap/ws_less/commit/521d76a838e65016edf637efde919b904b742dcb), but it's missing in the `ext_emconf.php` file which still indicates it would be compatible and installable in TYPO3 8 installations:

```php
'typo3' => '8.7.0-10.4.99',
```
https://github.com/svewap/ws_less/blob/master/ext_emconf.php#L37

**Comment by svewap** [comment]
Oh, thanks for the advice. Must have missed that when I merged. I will make a new release.
